### ISSUE TITLE
Update the firmware manually using the local ota package isn't working - 0.1.3 -> 0.1.4

### ISSUE THREAD

**Issue by s-nazim** [Seeed-Studio/reCamera#13]
Based on instruction 
https://wiki.seeedstudio.com/recamera_flash_os/
`/mnt/system/upgrade.sh start sg2002_reCamera_0.1.3_emmc_ota.zip
`
I've tried to update my system 0.1.3 to 0.1.4 based on my local build, but the process failed

`[recamera@reCamera]~$ /mnt/system/upgrade.sh start sg2002_reCamera_0.1.4_emmc_ota.zip 
Usage: /mnt/system/upgrade.sh start [q|x]
[recamera@reCamera]~$ /mnt/system/upgrade.sh start sg2002_reCamera_0.1.4_emmc_ota.zip x
Usage: /mnt/system/upgrade.sh start [q|x]
[recamera@reCamera]~$ /mnt/system/upgrade.sh start x sg2002_reCamera_0.1.4_emmc_ota.zip 
./upgrade.sh start is not running
[recamera@reCamera]~$ /mnt/system/upgrade.sh start q sg2002_reCamera_0.1.4_emmc_ota.zip 
0,null` 

Probably I missed something in your instructions

**Comment by s-nazim** [comment]
I think I found some update, the root cause that it hasn't been implemented 

https://github.com/Seeed-Studio/reCamera-OS/commit/c61b8219f5ea3605e97a3b78df2b14ed9f3637ea#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR7

**Comment by mingzhangqun** [comment]
> I think I found some update, the root cause that it hasn't been implemented
> 
> [c61b821#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR7](https://github.com/Seeed-Studio/reCamera-OS/commit/c61b8219f5ea3605e97a3b78df2b14ed9f3637ea#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR7)

Yes, the local upgrade is supported on 0.1.4. You can manually copy `/mnt/system/upgrade.sh` on 0.1.3 to use it.

**Comment by s-nazim** [comment]
Thanks!
